# If you want to enable automatic inclusion of Carbon Alpine on all pages,
# add this to your Settings
# Neos:
#   Neos:
#     fusion:
#       autoInclude:
#         Carbon.Alpine: true

Carbon:
  Alpine:
    includeOnPage: true
    useModules: true

    Main: true
    Files:
      Plugins:
        Ajax: false
        Anchor: false
        Clipboard: false
        Collapse: false
        Focus: false
        Intersect: false
        Mask: false
        Morph: false
        Persist: false
        Resize: false
        Sort: false
      UI:
        Combobox: false
        Dialog: false
        Disclosure: false
        ListBox: false
        Menu: false
        Popover: false
        Radio: false
        Switch: false
        Tabs: false
      Custom:
        Anchor: false
        Counter: false
        Fetch: false
        Focus: false
        Tash: false
        Tooltip: false
        TypeWriter: false
